### ISSUE TITLE
Google Search Console 設定

### ISSUE THREAD

**Issue by kobake** [fressets/fressets-web#18]
これ設定しておくとGoogle検索上位に来やすくなりますよ！
https://www.google.com/webmasters/tools/home?hl=ja

**Comment by visvirial** [comment]
日本語のページが一切インデックスされてない。
localizationの方法を変えないと駄目かも。

**Comment by visvirial** [comment]
![search console https fressets com](https://user-images.githubusercontent.com/6349067/37817844-72a39db4-2ebb-11e8-875f-92cba00f0f3b.png)

登録しました！
